# Generated by Django 4.2.1 on 2023-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_content',
            field=models.FileField(blank=True, upload_to='news/files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='article',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='news/img/%Y/%m/%d'),
        ),
    ]
