# Generated by Django 4.2.2 on 2023-07-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('VOICE', 'Voice'), ('STORY', 'Story'), ('MUSIC', 'Music'), ('TEXT', 'Text'), ('EXTRA', 'Extra')], default='VOICE', max_length=5),
        ),
    ]
