# Generated by Django 4.2.2 on 2023-07-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rid',
            field=models.CharField(default='sejin', max_length=20),
        ),
    ]
