# Generated by Django 4.2.2 on 2023-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rid',
        ),
        migrations.AddField(
            model_name='reporter',
            name='rid',
            field=models.CharField(default='sejin', max_length=20),
        ),
    ]
